version: '3.4'
services:
  php:
    image: jfernancordova/docker-laravel-api-dev:1.0.2
    environment:
      APP_NAME: docker-laravel-api-dev
      APP_ENV: local
      APP_DEBUG: "true"
      APP_KEY: base64:7BlG6pnoZqnN9sea8QOl34eSG0wVFWLUy9rso+HHumk=
      APP_LOG_LEVEL: debug
      APP_URL: "http://localhost"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_DATABASE: apiLaravelDocker
      DB_USERNAME: apiLaravelDocker
      DB_PASSWORD: apiLaravelDocker
      XDEBUG_MODE: 1
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:80"
    volumes:
      - .:/docker-laravel-api-dev

  db:
    image: mysql:5.7
    ports:
      - 13306:3306
    environment:
      MYSQL_DATABASE: apiLaravelDocker
      MYSQL_USER: apiLaravelDocker
      MYSQL_PASSWORD: apiLaravelDocker
      MYSQL_ROOT_PASSWORD: apiLaravelDocker
    volumes:
      - .docker/local-mysql-datadir:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: none

  react:
    image: jamesmalin/react-app:version3
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - 3000:3000
    # volumes:
    #   - .:/usr/src
    # environment:
    #   APP_NAME: docker-laravel-api-dev
    #   APP_ENV: local
    #   APP_DEBUG: "true"
    working_dir: /usr/src
    entrypoint: /bin/bash
    tty: true
   # command: npm cache clean -f && npm install -g n && n stable && create-react-app . && HOST=0.0.0.0 && npm start
